trigger:
  branches:
    include:
      - dev
      - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    node -v
    npm -v
  displayName: Verificar entorno

- script: |
    npm ci
  displayName: Instalar dependencias

- script: |
    npm run lint
  displayName: Lint

- script: |
    npm test
  displayName: Tests + Coverage

- script: |
    npm audit --audit-level=high
  displayName: Seguridad